### ISSUE TITLE
[ENH] Regularization option for solvers

### ISSUE THREAD

**Issue by JiaYaobo** [google/lineax#28]
Hi @patrick-kidger , thanks for your amazing `equinox` and `lineax` projects! 
I usually solve linear problems with regularization or penalization, like `ridge` regularization, It'll be nice if `lineax` has this feature! Existing library, `jaxopt` has a `ridge` parameter for their solvers, for example in their `solve_cg`, https://jaxopt.github.io/stable/_modules/jaxopt/_src/linear_solve.html#solve_cg, which seems not very hard to implement!
WDYT?

**Comment by packquickly** [comment]
Hello!

Generally we are unlikely to add something like this. Primarily because it's easy for the end user to do themselves and you could argue regularisation is something that should be handled before the call to a linear package, and not within the linear package.

In the inked JAXopt solve they implement ridge regression by taking a `ridge` parameter which I'll call `λ`, and redefining the matrix-vector multiplication: `Ax` becomes `Ax + λx`. Equivalently, they replace `A` with `A + λI` where I is the identity matrix.

In Lineax, if `A` is a matrix then the end user can replace `A` with `A + λI` and get the same result. If we don't want to materialise the whole matrix we can use `FunctionLinearOperator(f(x), input_structure)`, which becomes `FunctionLinearOperator(lambda x: f(x) + λ * x, input_structure)`.

**Comment by JiaYaobo** [comment]
@packquickly 

it makes sense! thanks!

**Comment by patrick-kidger** [comment]
I'll add that you can also do the regularisation directly on the operator, if you want to:
```python
operator = ...   # any operator at all
operator = operator + lambda * lineax.IdentityLinearOperator(operator.in_structure())
```

**Comment by JiaYaobo** [comment]
@patrick-kidger 
Yes, I notice `IdentityLinearOperator` api, things work well! thanks
